### PR TITLE
bump wrangler v3

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
The harvester uses the wrangler v3.
We need to bump to wrangler v3 here, or some CRD generator will get some trouble.

### CODE REVIEW

**Comment by Yu-Jack** [comment]
Add related issue https://github.com/harvester/harvester/issues/6249

**Review by Yu-Jack — APPROVED** [review]
LGTM

**Comment by Vicente-Cheng** [comment]
Force push to move the generated changes to a common update.

**Review by brandboat — APPROVED** [review]
LGTM!

**Comment by brandboat** [comment]
gentle ping @Vicente-Cheng , should we update node-manager version in harvester repo ?

**Comment by Vicente-Cheng** [comment]
yes, here is the PR https://github.com/harvester/harvester/pull/6250

**Pull request merged**
