### PR TITLE
common: fix random number generator

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
This is the side-effect from 97beeb7f7e1f1de4f0ca23be0d1c25a5a8f49097,
    the `Sign()` only return sign or not.
    Use `Int64()` will make it work as usual.

### CODE REVIEW

**Review by chrisho — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM

**Comment by Vicente-Cheng** [comment]
Hi all,
We use the random number generator on `harvester-installer`, `node-manager` and `node-disk-manager`.
So I prefer to wrap this into a common function and add a unit test.
This is the wrapper PR https://github.com/harvester/go-common/pull/5

Change this to draft, I will use this common function after the above PR is merged.

**Comment by Vicente-Cheng** [comment]
Hi all, update to using the wrapper function from go-common.
Please help to review it again.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]

**Review by chrisho — APPROVED** [review]

**Pull request merged**
