### PR TITLE
Upgrade wrangler to v2.1.0

### PR DESCRIPTION
**Pull request by connorkuehl**
**Problem:**

The current version of wrangler that node-manager depends on doesn't have the generic/fake package that supports mocking controllers, but my current patchset for another issue relies on that functionality for automated unit tests.

**Solution:**

Upgrade to the latest version of wrangler, so that the updated generic/fake package is available.

Also upgrade module github.com/google/gnostic to
836f55b2639b105f02aa6786b9c1ade794570ff8, to resolve a panic at runtime since the new dependency graph pulls in gnostic-models and there was some issue with gnostic+gnostic-models that is patched upstream now.

**Related Issue:** https://github.com/harvester/harvester/issues/4471

**Test plan:**

1. `make build ; make package`
2. `docker image save harvester/harvester-node-manager:a59a988-amd64 -o harvester-node-manager.tar`
3. `scp harvester-node-manager.tar rancher@HARVESTER-NODE:`
4. (on Harvester node) `ctr -n=k8s.io image import /home/rancher/harvester-node-manager.tar`
5. (on Harvester node)`kubectl patch managedchart harvester -n fleet-local -p='{"spec":{"paused":true}}' --type=merge`
6. (on Harvester node) `kubectl edit daemonset/harvester-node-manager -n harvester-system` (set image to the image tag of the container built in step 1)
7. (on Harvester node) `kubectl rollout restart daemonset/harvester-node-manager -n harvester-system`
8. (on Harvester node) `kubectl logs harvester-node-manager-ll5w5 -n harvester-system` -- just confirm there are no obvious issues and that the pod remains healthy

### CODE REVIEW

**Comment by connorkuehl** [comment]
ping

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by chrisho — APPROVED** [review]
LGTM and it works fine, thanks.

**Review by starbops — APPROVED** [review]
Swapped the image with the customized one, seems all good. LGTM, thanks!

**Pull request merged**
